theme: jekyll-theme-minimal
logo: 
title: ["Aslan: very(fi) prices"]
show_downloads: ["true"]
description: [For host my project of my undergraduate thesis]
Download:
  zip_url: https://github.com/Doctorspeppers/TCC/
  another_url: another value
